"""refactor ImageBlog

Revision ID: 60222f403512
Revises: e76ab7ff76c2
Create Date: 2025-12-14 19:37:45.714355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60222f403512"
down_revision: Union[str, Sequence[str], None] = "e76ab7ff76c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blog_images", sa.Column("path_to_file", sa.String(), nullable=False))
    op.drop_column("blog_images", "link_to_disk")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_images",
        sa.Column("link_to_disk", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("blog_images", "path_to_file")
    # ### end Alembic commands ###
