"""создание зависимостей

Revision ID: 374ec928684a
Revises: 29b16af6632d
Create Date: 2025-11-26 20:45:33.294375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "374ec928684a"
down_revision: Union[str, Sequence[str], None] = "29b16af6632d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("preview_image_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_projects_preview_image_id_images"),
        "projects",
        "images",
        ["preview_image_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_preview_image_id_images"),
        "projects",
        type_="foreignkey",
    )
    op.drop_column("projects", "preview_image_id")
    # ### end Alembic commands ###
