"""удаление caption, ordering

Revision ID: e74003ca19f6
Revises: 408bfe06531d
Create Date: 2025-12-12 16:04:16.848448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e74003ca19f6"
down_revision: Union[str, Sequence[str], None] = "408bfe06531d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "ordering")
    op.drop_column("images", "caption")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column("caption", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "images",
        sa.Column(
            "ordering", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
