"""основная таблица blog public_url nullabl= True

Revision ID: dc4c071f4b8c
Revises: 1817ab495d65
Create Date: 2025-12-19 02:28:12.459316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc4c071f4b8c"
down_revision: Union[str, Sequence[str], None] = "1817ab495d65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blogs", "path_to_file", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("blogs", "public_url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blogs", "public_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("blogs", "path_to_file", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
