"""создание зависимостей Blog BlogImage

Revision ID: 0e0c31a45f71
Revises: ea7c98e4c9d8
Create Date: 2025-12-10 15:46:26.941042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e0c31a45f71"
down_revision: Union[str, Sequence[str], None] = "ea7c98e4c9d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
