"""удаление ненужных полей BlogImage

Revision ID: 1a5517964dad
Revises: 0e0c31a45f71
Create Date: 2025-12-10 16:03:10.440981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a5517964dad"
down_revision: Union[str, Sequence[str], None] = "0e0c31a45f71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_images", "ordering")
    op.drop_column("blog_images", "caption")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_images",
        sa.Column("caption", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "blog_images",
        sa.Column("ordering", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
