"""сщздание таблиц зависимости

Revision ID: f664b23e3dbe
Revises: 52d48dbfea7d
Create Date: 2025-12-09 12:09:10.569524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f664b23e3dbe"
down_revision: Union[str, Sequence[str], None] = "52d48dbfea7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
