"""изменение link_dist на path_to_file

Revision ID: 408bfe06531d
Revises: 403d7dbe38c1
Create Date: 2025-12-12 16:01:45.201508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "408bfe06531d"
down_revision: Union[str, Sequence[str], None] = "403d7dbe38c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("path_to_file", sa.String(), nullable=False)
    )
    op.drop_column("images", "link_to_disk")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column(
            "link_to_disk", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("images", "path_to_file")
    # ### end Alembic commands ###
